WITH source AS (
    
    SELECT * 
    FROM {{source('google_search_console','keyword_page_report')}}

),final AS(

SELECT    
    COUNTRY::TEXT AS COUNTRY,
	DATE::DATE AS DATE,
	DEVICE::TEXT AS DEVICE,
	PAGE::TEXT AS PAGE,
	QUERY::TEXT AS QUERY,
	SEARCH_TYPE::TEXT AS SEARCH_TYPE,
	SITE::TEXT AS SITE,
	CLICKS::FLOAT AS CLICKS,
	IMPRESSIONS::FLOAT AS IMPRESSIONS,
	CTR::FLOAT AS CTR,
	POSITION::FLOAT AS POSITION,
	_FIVETRAN_SYNCED::TIMESTAMP_TZ AS _FIVETRAN_SYNCED
FROM source
)

SELECT * 
FROM final