version: 2
 
models:
 - name: google_search_console_keyword_page_report_source
   description: Base model for google search console data
   columns:
     - name: SITE
       tests:
         - not_null
     - name: DATE
       tests:
         - not_null
     - name: DEVICE
       tests:
         - not_null
     - name: COUNTRY
       tests:
         - not_null