version: 2

sources:
  - name: google_search_console
    database: '{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}'
    schema: google_search_console
    loaded_at_field: _fivetran_synced
    loader: fivetran
    description: Google Search Console data [Original Issue](https://gitlab.com/gitlab-data/analytics/-/issues/14526)

    quoting:
      database: true
      schema: false
      identifier: false

    tables:
      - name: KEYWORD_PAGE_REPORT