version: 2

models:
  - name: mart_product_usage_paid_user_metrics_monthly_workspace
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - snapshot_month
            - dim_subscription_id
            - delivery_type
            - uuid
            - hostname
            - dim_namespace_id
    columns:
      - name: snapshot_month
        tests:
          - not_null
      - name: dim_subscription_id
        tests:
          - not_null
      - name: dim_billing_account_id
        tests:
          - not_null
      - name: dim_crm_account_id
        tests:
          - not_null
      - name: dim_subscription_id_original
        tests:
          - not_null
      - name: snapshot_date_id
        tests:
          - not_null
      - name: delivery_type
        tests:
          - not_null
      - name: primary_key
        tests:
          - unique
          - not_null

  - name: wk_pump_gainsight_metrics_monthly_paid
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - snapshot_month
            - dim_subscription_id_original
            - uuid
            - hostname
            - dim_namespace_id
  
  - name: wk_fct_snowplow_events_service_ping
    columns:
      - name: behavior_structured_event_pk
        tests:
          - unique
          - not_null

  - name: wk_mart_snowplow_events_service_ping_metrics
    columns:
      - name: behavior_structured_event_pk
        tests:
          - unique
          - not_null

  - name: wk_rpt_user_based_metric_counts_namespace_monthly
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - date_month
            - ultimate_parent_namespace_id
            - metrics_path

  - name: redis_namespace_snowplow_clicks_workspace
    columns:
      - name: event_id
        tests:
          - unique
          - not_null
