version: 2

models:
  - name: mart_product_usage_paid_user_metrics_monthly_workspace
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - snapshot_month
            - dim_subscription_id
            - delivery_type
            - uuid
            - hostname
            - dim_namespace_id
    columns:
      - name: snapshot_month
        tests:
          - not_null
      - name: dim_subscription_id
        tests:
          - not_null
      - name: dim_billing_account_id
        tests:
          - not_null
      - name: dim_crm_account_id
        tests:
          - not_null
      - name: dim_subscription_id_original
        tests:
          - not_null
      - name: snapshot_date_id
        tests:
          - not_null
      - name: delivery_type
        tests:
          - not_null
      - name: primary_key
        tests:
          - unique
          - not_null

  - name: wk_fct_ping_instance_metric_gainsight_wave_monthly
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - snapshot_month
            - dim_subscription_id_original
            - dim_instance_id
            - hostname

  - name: wk_fct_saas_gainsight_metrics_monthly
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - snapshot_month
            - dim_subscription_id_original
            - dim_namespace_id

  - name: wk_rpt_gainsight_metrics_monthly_paid
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - snapshot_month
            - dim_subscription_id_original
            - delivery_type
            - uuid
            - hostname
            - dim_namespace_id
