version: 2

models:
  - name: marketo_activity_click_link_source_pii
  - name: marketo_activity_email_bounced_soft_source_pii
  - name: marketo_activity_email_bounced_source_pii
  - name: marketo_activity_fill_out_form_source_pii
  - name: marketo_activity_new_lead_source_pii
  - name: marketo_activity_push_lead_to_marketo_source_pii
  - name: marketo_activity_send_alert_source_pii
  - name: marketo_activity_sfdc_activity_source_pii
  - name: marketo_activity_sfdc_activity_updated_source_pii
  - name: marketo_activity_sync_lead_to_sfdc_source_pii
  - name: marketo_activity_unsubscribe_email_source_pii
  - name: marketo_activity_visit_webpage_source_pii