version: 2

models:
  - name: bizible_attribution_touchpoint_snapshots_source
    description: Attibtution touchpoints from Bizible loaded into Salesforce.
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - attribution_touchpoint_id
            - dbt_valid_from
  - name: bizible_touchpoint_snapshots_source
    description: Attibtution touchpoints from Bizible loaded into Salesforce.
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - touchpoint_id
            - dbt_valid_from
  - name: comp_band_loc_factor_base
    description: This model captures percent over comp band data from the sheetload_employee_location_factor snapshotted model. This sheetload is active between 2019.10  - 2020.05.20.
  - name: customers_db_customers_snapshots_base
    description: This is the base model for snapshotted customers data from the customers.gitlab.com database.
    columns:
      - name: customer_snapshot_id
        description: Auto-generated primary key when building the snapshot with dbt
        tests:
          - not_null
          - unique
      - name: customer_id
        tests:
          - not_null
      - name: valid_from
        tests:
          - not_null
      - name: valid_to
  - name: customers_db_orders_snapshots_base
    description: This is the base model for snapshotted orders data from the customers.gitlab.com database.
    columns:
      - name: order_snapshot_id
        description: Auto-generated primary key when building the snapshot with dbt
        tests:
          - not_null
          - unique
      - name: order_id
        tests:
          - not_null
      - name: valid_from
        tests:
          - not_null
      - name: valid_to

  - name: gitlab_dotcom_application_settings_snapshots_base
    description: This is the base model for snapshotted gitlab application settings data from the gitlab.com database.
    columns:
      - name: application_settings_snapshot_id
        description: Auto-generated primary key when building the snapshot with dbt.
        tests:
          - not_null
          - unique
      - name: application_settings_id
        tests:
          - not_null
  - name: gitlab_dotcom_gitlab_subscriptions_snapshots_base
    description: This is the base model for snapshotted gitlab subscriptions data from the gitlab.com database.
    columns:
      - name: gitlab_subscription_snapshot_id
        description: Auto-generated primary key when building the snapshot with dbt
        tests:
          - not_null
          - unique
      - name: gitlab_subscription_id
        tests:
          - not_null
      - name: valid_from
        tests:
          - not_null
      - name: valid_to
  - name: gitlab_dotcom_members_snapshots_base
    description: This is the base model for snapshotted members data from the gitlab.com database.
    columns:
      - name: member_snapshot_id
        description: Auto-generated primary key when building the snapshot with dbt
        tests:
          - not_null
          - unique
      - name: member_id
        tests:
          - not_null
      - name: valid_from
        tests:
          - not_null
      - name: valid_to
  - name: gitlab_dotcom_namespaces_snapshots_base
    description: This is the base model for snapshotted gitlab subscriptions data from the gitlab.com database.
    columns:
      - name: namespace_snapshot_id
        description: Auto-generated primary key when building the snapshot with dbt
        tests:
          - not_null
          - unique
      - name: namespace_id
        tests:
          - not_null
      - name: valid_from
        tests:
          - not_null
      - name: valid_to

  
  - name: gitlab_dotcom_project_statistics_snapshots_base
    description: Base model for Gitlab.com project statistics snapshot
    columns:
      - name: project_statistics_id
        tests:
          - not_null
      - name: project_id
        tests:
          - not_null

  - name: customers_db_licenses_snapshots_base
    description: This is the base model for snapshots from the licenses table from the customers database.
    columns:
      - name: license_snapshot_id
        description: Auto-generated primary key when building the snapshot with dbt.
        tests:
          - not_null
          - unique
      - name: license_id
        tests:
          - not_null
      - name: valid_from
        tests:
          - not_null
      - name: valid_to
 

  - name: license_db_licenses_snapshots_base
    description: This is the base model for snapshots from the licenses table from the license database.
    columns:
      - name: license_snapshot_id
        description: Auto-generated primary key when building the snapshot with dbt.
        tests:
          - not_null
          - unique
      - name: license_id
        tests:
          - not_null
      - name: valid_from
        tests:
          - not_null
      - name: valid_to

  - name: sfdc_account_snapshots_base_clean
    description: This is the clean base model for snapshots of the salesforce account table for 2019-10-01 and forward. This exists to make the UDF work.
  - name: sfdc_account_snapshots_base
    description: This is a view on the clean base model for snapshots of the salesforce account table for 2019-10-01 and forward.
    columns:
      - name: unique_key
        tests:
          - not_null
          - unique
      - name: account_snapshot_id
        tests:
          - not_null
      - name: id
          - not_null
      - name: valid_from
          - not_null
  - name: sfdc_account_snapshots_source
    description: This is the source model for snapshots of the salesforce account table for cleaning and renaming.
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - account_id
            - dbt_valid_from
    columns:
      - name: account_id
        tests:
          - not_null
      - name: dbt_valid_from
        tests:
          - not_null
      - name: zoom_info_company_name
        description: The name of the company matched by the Zoom Info enrichment process.
      - name: zoom_info_company_revenue
        description: The estimated revenue of the company matched by the Zoom Info enrichment process.
      - name: zoom_info_company_employee_count
        description: The number of employees of the company matched by the Zoom Info enrichment process.
      - name: zoom_info_company_industry
        description: The the primary industry of the company matched by the Zoom Info enrichment process.
      - name: zoom_info_company_city
        description: The city of the company matched by the Zoom Info enrichment process.
      - name: zoom_info_company_state_province
        description: The state or province of the company matched by the Zoom Info enrichment process.
      - name: zoom_info_company_country
        description: The country of the company matched by the Zoom Info enrichment process.
      - name: is_excluded_from_zoom_info_enrich
        description: A flag to indicate if the account should be included in the Zoom Info enrichment process.
  - name: sfdc_bizible_attribution_touchpoint_snapshots_source
    description: Attibtution touchpoints from Bizible loaded into Salesforce.
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - touchpoint_id
            - dbt_valid_from
  - name: sfdc_bizible_touchpoint_snapshots_source
    description: Attibtution touchpoints from Bizible loaded into Salesforce.
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - touchpoint_id
            - dbt_valid_from
  - name: sfdc_opportunity_snapshots_base
    description: This is the base model for snapshots of the salesforce opportunity table for 2019-10-01 and forward.
    columns:
      - name: unique_key
        tests:
          - not_null
          - unique
      - name: opportunity_snapshot_id
        tests:
          - not_null
      - name: id
          - not_null
      - name: valid_from
          - not_null
  - name: sfdc_user_snapshots_source
    description: This is the source model for snapshots of the salesforce user table for cleaning and renaming.
    columns:
      - name: id
          - not_null
      - name: dbt_valid_from
          - not_null
  - name: sheetload_comp_band_snapshot_base
    description: Captures % over comp band and is valid from 2020.10 onwards.        
  - name: zuora_account_snapshots_source
    description: Source layer for Zuora Accounts Snapshots for cleaning and renaming
  - name: zuora_amendment_snapshots_source
    description: Source layer for Zuora Amendments Snapshots for cleaning and renaming
  - name: zuora_contact_snapshots_source
    description: Source layer for Zuora Contacts Snapshots for cleaning and renaming
  - name: zuora_invoice_snapshots_source
    description: Source layer for Zuora Invoices Snapshots for cleaning and renaming
  - name: zuora_invoice_item_snapshots_source
    description: Source layer for Zuora Invoice Items Snapshots for cleaning and renaming
  - name: zuora_product_snapshots_source
    description: Source layer for Zuora Products Snapshots for cleaning and renaming
  - name: zuora_rate_plan_snapshots_source
    description: Source layer for Zuora Rate Plans Snapshots for cleaning and renaming
  - name: zuora_rate_plan_charge_snapshots_source
    description: Source layer for Zuora Rate Plan Charges Snapshots for cleaning and renaming
  - name: zuora_subscription_snapshots_source
    description: Source layer for Zuora Subscriptions
