config:
  partial_parse: true
gitlab-snowflake:
  target: dev
  outputs:
    dev:
      type: snowflake
      threads: 8
      account: gitlab
      user: rkohnke@gitlab.com # <-- This will be your GitLab email
      role: RKOHNKE # <-- Talk to your manager, usually, it is JSMITH for Jane Smith
      database: RKOHNKE # <-- JSMITH for Jane Smith
      warehouse: DEV_XS # <-- [ANALYST_XS, ENGINEER_XS], depends on your role
      schema: preparation
      authenticator: externalbrowser # <--- You must be logged in via OKTA

    # You can create targets for any warehouse that you have access to.
    dev_..:
      type: snowflake
      threads: 8
      account: gitlab
      user: rkohnke@gitlab.com # <-- This will be your GitLab email
      role: RKOHNKE # <-- Talk to your manager, usually, it is JSMITH for Jane Smith
      database: RKOHNKE # <-- JSMITH for Jane Smith
      warehouse: DEV_XS # <-- depends on your role
      schema: preparation
      authenticator: externalbrowser # <--- You must be logged in via OKTA

    docs:
      type: snowflake
      threads: 8
      account: gitlab
      user: rkohnke@gitlab.com # <-- This will be your GitLab email
      role: RKOHNKE # <-- Talk to your manager, usually, it is JSMITH for Jane Smith
      database: RKOHNKE # <-- JSMITH for Jane Smith
      warehouse: DEV_XS # <-- [ANALYST_XS, ENGINEER_XS], depends on your role
      schema: preparation
      authenticator: externalbrowser # <--- You must be logged in via OKTA
