version: 2

models:
  - name: sheetload_xactly_credit
    description: Sheetload of Xactly credits loaded manually as a workaround while we finalize Xactly Sales Attainment modeling
  - name: xactly_fy23_quota
    description: Sheetload file load of FY23 quota from Xactly used temporarily as we work on Xactly Sales Attainment modeling
  - name: rpt_deleted_crm_account_on_billing_account
    description: Zuora billing accounts with the original CRM account id, and the merged CRM account id computed in the data warehouse. This will be used to create a report for the billing team to track Zuora accounts associated with deleted CRM accounts.
  - name: sheetload_fy24_placeholder_target
    description: Placeholder targets loaded to test the new target structure ahead of the new fiscal year.
models:
  - name: wk_sales_clari_net_arr_forecast
    description: Forecast table combining the different API sub-payloads together
    columns:
      - name: user_full_name
        tests:
          - not_null
      - name: email
        tests:
          - not_null
      - name: crm_user_id
        tests:
          - not_null
      - name: sales_team_role
        tests:
          - not_null
      - name: parent_role
      - name: fiscal_quarter
        tests:
          - not_null
      - name: field_name
        tests:
          - not_null
      - name: week_number
        tests:
          - not_null
      - name: week_start_date
        tests:
          - not_null
      - name: week_end_date
        tests:
          - not_null
      - name: field_type
        tests:
          - not_null
      - name: forecast_value
      - name: is_updated
