version: 2

models:
  - name: mart_crm_opportunity_stamped_hierarchy_hist
    description: >-
      Model with single pane of glass over the sales and marketing metrics.
      It differs from `mart_crm_opportunity` by using the live sales hierarchy, from the account object, for the stamped fields
      when the fiscal year is below the current one.
      Also, for the `alliance_type` field it has the current state of the field instead of the historical version of it. For example,
      instead of showing the value Non-Alliance it shows Channel Partners.
    columns:
      - name: dim_crm_opportunity_id
        tests:
            - not_null
            - unique
      - name: arr_created_date
        description: A Salesforce [formula field](https://gitlab.my.salesforce.com/00N4M00000ISAEK) that This tracks the date that the ARR was added to an opportunity. 
      - name: net_arr_created_date
        description: A renaming of `created_date` used by SS&A to report on pipeline creation. 
      - name: pipeline_created_date
        description: A renaming of A Salesforce [formula field](https://gitlab.my.salesforce.com/00N4M00000ISAEK) that This tracks the date that the ARR was added to an opportunity. This is used in SS&A pipeline reporting.
  - name: sheetload_xactly_credit
    description: Sheetload of Xactly credits loaded manually as a workaround while we finalize Xactly Sales Attainment modeling
  - name: xactly_fy23_quota
    description: Sheetload file load of FY23 quota from Xactly used temporarily as we work on Xactly Sales Attainment modeling
