version: 2

models:
  - name: mart_crm_opportunity_stamped_hierarchy_hist
    description: >-
      Model with single pane of glass over the sales and marketing metrics.
      It differs from `mart_crm_opportunity` by using the live sales hierarchy, from the account object, for the stamped fields
      when the fiscal year is below the current one.
      Also, for the `alliance_type` field it has the current state of the field instead of the historical version of it. For example,
      instead of showing the value Non-Alliance it shows Channel Partners.
    columns:
      - name: dim_crm_opportunity_id
        tests:
            - not_null
            - unique
  - name: sheetload_xactly_credit
    description: Sheetload of Xactly credits loaded manually as a workaround while we finalize Xactly Sales Attainment modeling
  - name: xactly_fy23_quota
    description: Sheetload file load of FY23 quota from Xactly used temporarily as we work on Xactly Sales Attainment modeling
