version: 2

sources:
  - name: gcp_billing
    database: '{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}'
    schema: gcp_billing
    loaded_at_field: uploaded_at
    loader: Airflow, gcp_billing
    description: GCP Billing Data from Bigquery [Original Issue](https://gitlab.com/gitlab-data/analytics/-/issues/5268)

    quoting:
      database: true
      schema: false
      identifier: false

    freshness:
      warn_after: {count: 24, period: hour}
      error_after: {count: 48, period: hour}

    tables:
      - name: gcp_billing_export_combined
      - name: test_summary_gcp_billing
