version: 2

sources:
  - name: gcp_billing
    database: '{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}'
    schema: gcp_billing
    loaded_at_field: uploaded_at
    loader: Airflow, gcp_billing
    description: GCP Billing Data from Bigquery [Original Issue](https://gitlab.com/gitlab-data/analytics/-/issues/5268)

    quoting:
      database: true
      schema: false
      identifier: false

    freshness:
      warn_after: {count: 24, period: hour}
      error_after: {count: 48, period: hour}

    tables:
      - name: gcp_billing_export_combined

      - name: test_summary_gcp_billing

      - name: detail_gcp_billing
        description: "GCP Billing detail table exported from bigQuery"
        external:
          location: "@raw.gcp_billing.GCP_BILLING_GCS_EXPORT/detail"
          file_format: "( type = parquet )"
          auto_refresh: false
          partitions:
            - name: date_part
              data_type: date
              expression: to_date(split_part(metadata$filename, '/', 2),'YYYY-MM-DD')
        columns:
          - name: _partition_date
            data_type: date
          - name: gcs_export_time
            data_type: number
          - name: adjustment_info
            data_type: varchar
          - name: billing_account_id
            data_type: varchar
          - name: cost
            data_type: float
          - name: cost_type
            data_type: varchar
          - name: credits
            data_type: array
          - name: currency
            data_type: varchar
          - name: currency_conversion_rate
            data_type: float
          - name: export_time
            data_type: number
          - name: invoice
            data_type: object
          - name: labels
            data_type: array
          - name: location
            data_type: object
          - name: project
            data_type: object
          - name: resource
            data_type: varchar
          - name: service
            data_type: object
          - name: sku
            data_type: object
          - name: system_labels
            data_type: array
          - name: usage
            data_type: object
          - name: usage_end_time
            data_type: number
          - name: usage_start_time
            data_type: number
            
      - name: summary_gcp_billing
        description: "GCP Billing detail table exported from bigQuery"
        external:
          location: "@raw.gcp_billing.GCP_BILLING_GCS_EXPORT/summary"
          file_format: "( type = parquet )"
          auto_refresh: false
          partitions:
            - name: date_part
              data_type: varchar
              expression: split_part(metadata$filename, '/', 2)
        columns:
          - name: _partition_date
            data_type: date
          - name: gcs_export_time
            data_type: timestamp
          - name: adjustment_info
            data_type: varchar
          - name: billing_account_id
            data_type: varchar
          - name: cost
            data_type: float
          - name: cost_type
            data_type: varchar
          - name: credits
            data_type: array
          - name: currency
            data_type: varchar
          - name: currency_conversion_rate
            data_type: float
          - name: export_time
            data_type: number
          - name: invoice
            data_type: object
          - name: labels
            data_type: array
          - name: location
            data_type: object
          - name: project
            data_type: object
          - name: service
            data_type: object
          - name: sku
            data_type: object
          - name: system_labels
            data_type: array
          - name: usage
            data_type: object
          - name: usage_end_time
            data_type: number
          - name: usage_start_time
            data_type: number