version: 2

sources:
  - name: gcp_billing
    database: '{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}'
    schema: gcp_billing
    loaded_at_field: uploaded_at
    loader: Airflow, gcp_billing
    description: GCP Billing Data from Bigquery [Original Issue](https://gitlab.com/gitlab-data/analytics/-/issues/5268)

    quoting:
      database: true
      schema: false
      identifier: false

    freshness:
      warn_after: {count: 24, period: hour}
      error_after: {count: 48, period: hour}

    tables:
      - name: gcp_billing_export_combined
      - name: dbt_test_detail_gcp_billing
        description: "GCP Billing detail table exported from bigQuery"
        external:
          location: "@raw.gcp_billing.GCP_BILLING_GCS_EXPORT/test_detail"
          file_format: "( type = parquet )"      # fully specified here, or reference an existing file format
          auto_refresh: false                  # requires configuring an event notification from Amazon S3 or Azure
          partitions:
            - name: date_part
              data_type: date
              expression: to_date(split_part(metadata$filename, '/', 2),'YYYY_MM_DD')
        
