version: 2

models:
  - name: wk_marketo_activity_click_link_pii
  - name: wk_marketo_activity_email_bounced_pii
  - name: wk_marketo_activity_email_bounced_soft_pii
  - name: wk_marketo_activity_fill_out_form_pii
  - name: wk_marketo_activity_new_lead_pii
  - name: wk_marketo_activity_push_lead_to_marketo_pii
  - name: wk_marketo_activity_send_alert_pii
  - name: wk_marketo_activity_sfdc_activity_pii
  - name: wk_marketo_activity_sfdc_activity_updated_pii
  - name: wk_marketo_activity_sync_lead_to_sfdc_pii
  - name: wk_marketo_activity_visit_webpage_pii
  - name: wk_marketo_activity_unsubscribe_email_pii
