version: 2

models:
    - name: fct_book_rating
      description: Data tracer bullet project which analyzes the book ratings of over 11k books.
      columns:
        - name: dim_book_id
            - not_null
            - unique
        - name: dim_author_id
            - not_null
            - unique
        - name: dim_publisher_id
            - not_null
            - unique
        - name: dim_publication_date_id
            - not_null
            - unique
        - name: ratings_count
            - not_null   
        - name: text_reviews_count
            - not_null  
        - name: average_rating
            - not_null       
    - name: dim_book
      description: Data tracer bullet project which analyzes the book ratings of over 11k books.
      columns:
        - name: isbn
            - not_null
            - unique
        - name: dim_book_id
            - not_null
            - unique
        - name: language
            - not_null        
        - name: book_title
            - not_null
            - unique
        - name: pages_count
            - not_null  
    - name: dim_author
      description: Data tracer bullet project which analyzes the book ratings of over 11k books.
      columns:
        - name: dim_author_id
          tests:
            - not_null
            - unique
        - name: author_name
            - not_null
    - name: dim_publisher
      description: Data tracer bullet project which analyzes the book ratings of over 11k books.
      columns:
        - name: dim_publisher_id
          tests:
            - not_null
            - unique
        - name: publisher
            - not_null