version: 2

models:
    - name: key_assets_source
      description: "Key assets list as extracted from Monte Carlo."
    - name: monitors_source
      description: "Monte Carlo monitors."
    - name: cleanup_suggestions_source
      description: "Monte Carlo clanup suggestions."
    - name: custom_rules_source
      description: "Monte Carlo custom rules."
    - name: dashboard_analytics_source
      description: "Monte Carlo dashboard analytics, such as number of issues, types of issues etc."
    - name: field_cleanup_suggestions_source
      description: "Monte Carlo field cleanup suggestions, based on how often these columns are used in queries."
    - name: incident_history_source
      description: "Monte Carlo list of incidents."
    - name: monitor_issues_and_solutions_source
      description: "Monte Carlo list of issues and solutions."
    - name: monitor_recom_dimension_tracking_source
      description: "Monte Carlo exported table on dimension tracking monitors."
    - name: rca_query_change_source
      description: "Monte Carlo exported data of RCA query changes."
    - name: table_read_write_stats_source
      description: "Monte Carlo exported list of statistics on table reads and writes."
    - name: top_queries_per_executor_source
      description: "Monte Carlo exported list top queries."
    - name: monitor_recom_field_health_source
      description: "Monte Carlo exported field health information."
    - name: events_source
      description: "Monte Carlo exported list of events."
      