version: 2

sources:
  - name: monte_carlo_prod_insights
    database: "MONTE_CARLO"
    schema: prod_insights
    loader: Snowflake Data Exchange

    quoting:
      database: true
      schema: false
      identifier: false

    tables:
      - name: key_assets
        identifier: key_assets
      - name: monitors
        identifier: monitors
      - name: cleanup_suggestions
        identifier: cleanup_suggestions
      - name: custom_rules
        identifier: custom_rules
      - name: dashboard_analytics
        identifier: dashboard_analytics
      - name: field_cleanup_suggestions
        identifier: field_cleanup_suggestions
      - name: incident_history
        identifier: incident_history
      - name: monitor_issues_and_solutions
        identifier: monitor_issues_and_solutions
      - name: monitor_recom_dimension_tracking
        identifier: monitor_recom_dimension_tracking
      - name: rca_query_change
        identifier: rca_query_change
      - name: table_read_write_stats
        identifier: table_read_write_stats
      - name: top_queries_per_executor
        identifier: top_queries_per_executor
      - name: monitor_recom_field_health
        identifier: monitor_recom_field_health
      - name: events
        identifier: events