version: 2

models:
  - name: test_gcp_billing_source
    description: Base model for gcp billing export
    columns:
      - name: primary_key
        tests:
          - not_null
          - unique
      - name: billing_account_id
        tests:
          - not_null
