version: 2

models:
  - name: mart_usage_ping
    description: '{{ doc("mart_usage_ping") }}'
    columns:
      - name: dim_usage_ping_id
        tests:
          - not_null
          - unique
      - name: dim_instance_id
        tests:
          - not_null
      - name: dim_date_id
        tests:
          - not_null
