version: 2
models:

  - name: container_registry_download_logs_source
    description: The list of ip that are available to users of google cloud services.

    columns:
      - name: correlation_id
        description: An identifier used to connect different parts of the logs together.
        tests:
          - unique
      - name: downloaded_at
        description: The timestamp of when the download occurred.
      - name: root_repository
        description: The top, or root, of the location of the container.
      - name: container_path
        description: The full path of the location of the container
      - name: container_digest
        description: Unique identifier for the container that was downloaded.
      - name: download_size_bytes
        description: The size of the downloaded container.
      - name: downloaded_by_ip
        description: The ip that was logged as having downloaded the container.
      - name: downloaded_by_parsed_ip
        description: The object generated by the `PARSE_IP` function from Snowflake.
      - name: downloaded_by_ipv4
        description: The ipv4 number, derived using the `PARSE_IP` function from Snowflake.
      - name: downloaded_by_hex_ipv4
        description: The ipv4 number in hexadecimal format.  This is generated to simplify joining logic in downstream tables.
      - name: downloaded_by_hex_ipv6
        description: The ipv6 number in hexadecimal format, derived using the `PARSE_IP` function from Snowflake.
      - name: downloaded_by_hex_ip
        description: The hexadecimal format of the ip.
      - name: downloaded_by_ip_type
        description: Indicates if the original ip was in ipv4 or ipv6 format.