version: 2
models:
  - name: customers_db_customers_pii
    description: Model for Customers sensitive data
    columns:
        - name: customer_id
          tests:
              - not_null
              - unique
  - name: customers_db_license_versions
    description: Model for License Versions sensitive data
    columns:
        - name: item_id
          tests:
              - not_null
