version: 2

models:
  - name: test_gcp_billing_export_xf
    description: Final model for billing export.
    columns:
      - name: source_primary_key
        tests:
          - not_null

  - name: test_gcp_billing_export_credits
    description: table for unnested credit rows
    columns:
      - name: credit_pk
        tests:
          - not_null
      - name: source_primary_key
        tests:
          - not_null

  - name: test_gcp_billing_export_resource_labels
    description: table for unnested resource label rows
    columns:
      - name: resource_label_pk
        tests:
          - not_null
      - name: source_primary_key
        tests:
          - not_null

  - name: test_gcp_billing_export_project_labels
    description: table for unnested project label rows
    columns:
      - name: project_label_pk
        tests:
          - not_null
      - name: source_primary_key
        tests:
          - not_null

  - name: test_gcp_billing_export_system_labels
    description: table for unnested system label rows
    columns:
      - name: system_label_pk
        tests:
          - not_null
      - name: source_primary_key
        tests:
          - not_null
