version: 2

models:
  - name: bdg_company_domain_account
  - name: wk_fct_user_namespace_account_company
    columns:
      - name: user_namespace_account_company_pk
        tests:
          - unique
  - name: wk_mart_namespace_company_account
  - name: rpt_namespace_company_account
  - name: map_project_namespace
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - dim_project_sk
            - dim_namespace_sk
    columns:
      - name: dim_project_sk
        tests:
          - unique
          - not_null
      - name: dim_namespace_sk
        tests:
          - unique
          - not_null
          
  - name: wk_fct_direct_membership
    columns:
      - name: direct_member_pk
        tests:
          - unique

  - name: wk_fct_group_share
    columns:
      - name: group_share_pk
        tests:
          - unique