version: 2

models:
    - name: mart_crm_attribution_touchpoint
      description: Model containing Bizible attribution touchpoints along with contact, lead, account, campaign, and opportunity details.
      columns:
        - name: dim_crm_touchpoint_id
          tests:
              - not_null
              - unique

    - name: mart_crm_touchpoint
      description: Model containing Bizible touchpoints (non-attribution) along with contact, lead, account, and campaign details.
      columns:
        - name: dim_crm_touchpoint_id
          tests:
            - not_null
            - unique:
                config:
                  error_if: ">3"
                  warn_if: ">1"

    - name: mart_crm_person
      description: Model with person and MQL business logic.
      columns:
        - name: dim_crm_person_id
          tests:
              - not_null
              - unique
          tags: ["tdf", "mart", "sales_funnel"]

    - name: mart_marketing_contact_no_pii
      description: Non sensitive version of the mart_marketing_contact model.
