version: 2

models:
  - name: wk_self_managed_spo
    description: Workspace model that builds a MVC for Self-Managed SPO and SPU KPIs.
    columns:
      - name: organization_id
        description: A unique id that is a combination of the host_name and dim_instance_id.
        tests:
          - not_null
      - name: delivery
        description: delivery is based on the product category name and is either SaaS or Self-Managed delivery.
        tests:
          - not_null
      - name: organization_type
        description: segmentation for organization type. Values - Group, Individual, User
        tests:
          - not_null
          - accepted_values:
              values: ['Group','Individual']
      - name: active_stage_count
        description: number of active stages for a given organization in a given month


  - name: wk_saas_spo
    description: Workspace model that shows monthly Stages per Organization data on a namespace-level for SaaS.
    columns:
      - name: reporting_month
        description: Month in which the product usage was reported.
        tests:
          - not_null
      - name: organization_id
        description: Top-level namespace id.
        tests:
          - not_null
      - name: delivery
        description: delivery is based on the product category name and is either SaaS or Self-Managed delivery.
        tests:
          - not_null
      - name: organization_type
        description: segmentation for organization type. Values - Group, Individual, User
        tests:
          - not_null
          - accepted_values:
              values: ['Group','Individual','User']
      - name: product_tier
        description: segmentation for Product Tier. Values - Core (CE, EE), Starter, Premium, Ultimate, NULL
        tests:
          - not_null
      - name: is_paid_product_tier
        description: Denotes whether the organization is on a paid product tier at the time of reporting.
        tests:
          - not_null
      - name: active_stage_count
        description: number of active stages for a given organization in a given month

  - name: wk_usage_ping_geo_node_usage
    description: Extract and flatten data from the geo nodes
    columns:
      - name: instance_path_id
        description: the unique ID for the combination of the ping_id and the path (unique service ping identifier and the metrics path).
        tests:
          - not_null
          - unique