version: 2

models:
  - name: google_search_console_keyword_page_report
    description: '{{ doc("google_search_console_keyword_page_report_docs") }}'
    columns:
      - name: country
        description: The country where the search came from; for example, Canada or Mexico.
      - name: date
        description: The date when the site against the particular record was visited.
      - name: device
        description: The type of device on which the user is searching - desktop, tablet, or mobile.
      - name: page
        description: The final URL linked by a Search result after any skip redirects
      - name: query
        description: These are the query strings that users searched for on Google. Only non-anonymized query strings that returned your site are shown.
      - name: search_type
        description: Which search tab contained the link seen by the user - Web, Image, Video and/or News.
      - name: site
        description: The site which was visited i.e. https://gitlab.com, http://gitlab.com or https://about.gitlab.com .
      - name: clicks
        description: Count of clicks from a Google search result that landed the user on your property.
      - name: impressions
        description: How many links to your site a user saw on Google search results. Impressions are counted when the user visits that page of results, even if the result was not scrolled into view. 
      - name: ctr
        description:  Click-through rate- the click count divided by the impression count. If a row of data has no impressions, the CTR will be shown as a dash (-) because CTR would be division by zero.
      - name: position
        description: The position value in the table represents the average position in search results for the URL.
      - name: _fivetran_synced
        description: Timestamp when fivetran synced/bought in the particular record.