version: 2

models:
  - name: dim_website_page
    description: Dimension for the analysis of webpages used according to the page_urlpath in Snowplow.
    columns:
      - name: dim_website_page_sk
        tests:
          - not_null
          - unique

  - name: fct_behavior_structured_events
    description: Atomic fact of [Snowplow structured events](https://docs.gitlab.com/ee/development/snowplow/#structured-event-taxonomy).
    columns: 
      - name: behavior_unstructured_event_pk
        tests:
          - not_null
          - unique

  - name: fct_behavior_structured_events_experiment
    description: Snowplow structured events filtered related to experiments, enriched with attributes of the experiment.
    columns: 
      - name: behavior_unstructured_event_pk
        tests:
          - not_null
          - unique

  - name: fct_behavior_structured_without_assignment
    description: Snowplow structured events filtered to remove assignment events for performance improvements.
    columns: 
      - name: behavior_unstructured_event_pk
        tests:
          - not_null
          - unique

  - name: fct_behavior_structured_redis_hll_counters
    description: Snowplow structured events filtered to Redis metrics.
    columns: 
      - name: behavior_unstructured_event_pk
        tests:
          - not_null
          - unique

  - name: fct_website_page_view
    description: TBD
    columns:
      - name: website_page_view_pk
        tests:
          - not_null
          - unique