version: 2

models:
  - name: dim_behavior_website_page
    description: Dimension for the analysis of webpages used according to the page_urlpath in Snowplow. It is unique on `clean_url_path`, `page_url_host` and `app_id`.
    columns:
      - name: dim_behavior_website_page_pk
        tests:
          - not_null
          - unique

  - name: fct_behavior_structured_event
    description: Atomic fact of [Snowplow structured events](https://docs.gitlab.com/ee/development/snowplow/#structured-event-taxonomy).
    columns: 
      - name: behavior_structured_event_pk
        tests:
          - not_null
          - unique

  - name: fct_behavior_structured_event_experiment
    description: Snowplow structured events filtered related to experiments, enriched with attributes of the experiment.
    columns: 
      - name: behavior_structured_event_pk
        tests:
          - not_null
          - unique

  - name: fct_behavior_structured_event_without_assignment
    description: Snowplow structured events filtered to remove assignment events for performance improvements.
    columns: 
      - name: behavior_structured_event_pk
        tests:
          - not_null
          - unique

  - name: fct_behavior_structured_event_redis_hll_counters
    description: Snowplow structured events filtered to Redis metrics.
    columns: 
      - name: behavior_structured_event_pk
        tests:
          - not_null
          - unique
          
  - name: fct_behavior_website_page_view
    description: TBD
    columns:
      - name: behavior_website_page_view_pk
        tests:
          - not_null
          - unique

  - name: prep_snowplow_structured_event_all_source
    description: Model combining all monthly partitions of Snowplow structured events. This will take a sample of strutured events if the model is not run incrementally.

  - name: fct_behavior_website_link_click
    description: Fact table containing details of links clicked.
    columns: 
      - name: fct_behavior_website_link_click_pk
        tests:
          - not_null
          - unique

  - name: dim_behavior_website_event
    description: Dimensional model containing distinct events types from Snowplow.
    columns:
      - name: dim_behavior_website_event_pk
        tests:
          - not_null
          - unique
