version: 2

models:
  - name: dim_behavior_browser
    description: Dimension for the analysis of browsers in Snowplow.
    columns: 
      - name: dim_behavior_browser_sk
        tests:
          - not_null
          - unique

  - name: dim_behavior_operating_system
    description: Dimension for the analysis of operating systems in Snowplow.
    columns: 
      - name: dim_behavior_operating_system_sk
        tests:
          - not_null
          - unique

  - name: dim_behavior_website_page
    description: Dimension for the analysis of webpages used according to the page_urlpath in Snowplow.
    columns:
      - name: dim_behavior_website_page_sk
        tests:
          - not_null
          - unique

  - name: fct_behavior_website_page_view
    description: Page views are a subset of Snowplow events and are fired by the Javascript tracker.
    columns:
      - name: fct_behavior_website_page_view_sk
        tests:
          - not_null
          - unique

  - name: prep_snowplow_structured_event_all_source
    description: Model combining all monthly partitions of Snowplow structured events. This will take a sample of structured events if the model is not run incrementally.

  - name: fct_behavior_link_click
    description: A derived fact from fct_behavior_unstructured_event containing only link_click event types.
    columns: 
      - name: fct_behavior_unstructured_sk
        tests:
          - not_null
          - unique

  - name: dim_behavior_event
    description: Dimensional model containing distinct events types from Snowplow.
    columns:
      - name: dim_behavior_event_sk
        tests:
          - not_null
          - unique

  - name: fct_behavior_structured_event
    description: Atomic fact table for structured events.
    columns:
      - name: fct_behavior_structured_sk
        tests:
          - not_null
          - unique

  - name: fct_behavior_structured_event_experiment
    description: Derived fact table for structured events related to experiments.
    columns:
      - name: fct_behavior_structured_sk
        tests:
          - not_null
          - unique

  - name: fct_behavior_structured_event_redis_hll_counters
    description: Derived fact table for structured events related to redis hll metrics.
    columns:
      - name: fct_behavior_structured_sk
        tests:
          - not_null
          - unique

  - name: fct_behavior_structured_event_without_assignment
    description: Derived fact table for structured events without assignment events.
    columns:
      - name: fct_behavior_structured_sk
        tests:
          - not_null
          - unique

  - name: fct_behavior_structured_event_without_assignment_190
    description: Derived fact table for structured events without assignment events filtered to the last 190 days.
    columns:
      - name: fct_behavior_structured_sk
        tests:
          - not_null
          - unique

  - name: fct_behavior_structured_event_without_assignment_400
    description: Derived fact table for structured events without assignment events fitlered to the last 400 days.
    columns:
      - name: fct_behavior_structured_sk
        tests:
          - not_null
          - unique

  - name: fct_behavior_unstructured_event
    description: Atomic fact table for unstructured events.
    columns:
      - name: fct_behavior_unstructured_sk
        tests:
          - not_null
          - unique

  - name: prep_snowplow_unnested_events_all
    description: This is the primary events view which is the union of the Fishtown and GitLab tables across all snowplow_YYYY_MM schemas. All of the unstructured events are unpacked - [link click tracking](https://github.com/snowplow/snowplow/wiki/2-Specific-event-tracking-with-the-Javascript-tracker#39-link-click-tracking), [form tracking](https://github.com/snowplow/snowplow/wiki/2-Specific-event-tracking-with-the-Javascript-tracker#3101-enableformtracking), and [time tracking](https://github.com/snowplow/snowplow/wiki/2-Specific-event-tracking-with-the-Javascript-tracker#timing).
    columns:
      - name: event_id
        tests:
          - not_null
          - unique

  - name: prep_snowplow_unstructured_events_all
    description: This a view over all snowplow_YYYY_MM schemas for unstructured events.
    columns:
      - name: event_id
        tests:
          - not_null
          - unique



