version: 2

sources:
  - name: zoominfo
    database: "ZOOMINFO_INBOUND"
    schema: gitlab
    loader: Snowflake Data Exchange
    
    quoting:
      database: true
      schema: false
      identifier: false

    tables:
      - name: global
        identifier: zi_comp_with_linkages_20220101_global         
        description: International table, data ingested from Zoominfo inbound share.
     
      - name: techs
        identifier: zi_reference_techs_20210901         
        description: Technograph table,  data ingested from Zoominfo inbound share.
           
      - name: contact_enhance
        identifier: gitlab_contact_enhance_10_25_21         
        description: User company matched table which appends company information to the user list Gitlab sends to zoominfo. Data ingested from Zoominfo inbound share.
