version: 2

sources:
  - name: zuora_query_api
    tags: ["tdf", "zuora", "zuora_query_api"]
    database: '{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}'
    schema: zuora_query_api
    loader: Airflow
    loaded_at_field: TO_TIMESTAMP_NTZ(CAST(_uploaded_at AS INT))::TIMESTAMP

    quoting:
      database: true
      schema: false
      identifier: false

    freshness:
      warn_after: {count: 24, period: hour}
      error_after: {count: 36, period: hour}

    tables:
      - name: users
      - name: order_action_rate_plan
        identifier: orderactionrateplan