version: 2

models:
  - name: google_ads_ad_group_hourly_stats_source
    description: Base model for gcp billing export
    columns:
      - name: hourly_stats_id
        tests:
          - not_null
      - name: customer_id
        tests:
          - not_null
  - name: google_adds_ad_group_history_source
    columns:
      - name: ad_group_id
        tests:
          - not_null
  - name: google_adds_ad_history_source
    columns:
      - name: ad_id
        tests:
          - not_null
  - name: google_adds_ad_stats_source
  - name: google_adds_campaign_history_source
    columns:
      - name: campaign_id
        tests:
          - not_null
  - name: google_adds_expanded_text_ad_history_source

