version: 2

models:
  - name: google_ads_ad_group_hourly_stats_source
    description: Base model for gcp billing export
    columns:
      - name: hourly_stats_id
        tests:
          - not_null
      - name: customer_id
        tests:
          - not_null
  - name: google_ads_ad_group_history_source
    tests:
        - dbt_utils.unique_combination_of_columns:
            combination_of_columns:
              - ad_group_id
              - ad_group_updated_at
    columns:
      - name: ad_group_id
        tests:
          - not_null
      - name: ad_group_updated_at
        tests:
          - not_null
  - name: google_ads_ad_history_source
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - ad_id
            - ad_updated_at
            - ad_group_id
    columns:
      - name: ad_id
        tests:
          - not_null
      - name: ad_updated_at
        tests:
          - not_null
      - name: ad_group_id
        tests:
          - not_null
  - name: google_ads_ad_stats_source
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - ad_stats_date
            - ad_id
            - device
            - ad_network_type
            - customer_id
    columns:
      - name: ad_stats_date
        tests:
          - not_null
      - name: ad_id
        tests:
          - not_null
      - name: device
        tests:
          - not_null
      - name: ad_network_type
        tests:
          - not_null
      - name: customer_id
        tests:
          - not_null
  - name: google_ads_campaign_history_source
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - campaign_id
            - campaign_updated_at
    columns:
      - name: campaign_id
        tests:
          - not_null
      - name: campaign_updated_at
        tests:
          - not_null
  - name: google_ads_expanded_text_ad_history_source
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - ad_id
            - ad_group_id
            - ad_text_updated_at
    columns:
      - name: ad_id
        tests:
          - not_null
      - name: ad_group_id
        tests:
          - not_null
      - name: ad_text_updated_at
        tests:
          - not_null

