version: 2

sources:
  - name: google_ads
    database: '{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}'
    schema: google_ads
    loaded_at_field: _fivetran_synced
    loader: fivetran
    description: Google Ads data [Original Issue](https://gitlab.com/gitlab-data/analytics/-/issues/11519)

    quoting:
      database: true
      schema: false
      identifier: false

    freshness:
      warn_after: {count: 24, period: hour}
      error_after: {count: 48, period: hour}

    tables:
      - name: ad_group_hourly_stats
