version: 2
models:
- name: sheetload_abm_account_baselines
- name: sheetload_abuse_mitigation
  description: Abuse currently manually pulls data from Bouncer (Abuse mitigation Tool) in order to report on abusive account mitigation.
- name: sheetload_abuse_top_ci_data
  description: Trust and Safety currently tracks top ci usage and report on the volume implicated in abuse.
- name: sheetload_abuse_top_download_data
  description: Trust and Safety currently tracks top downloaded content and report on the volume implicated in abuse.
- name: sheetload_abuse_top_storage_data
  description: Trust and Safety currently tracks largest namespaces and report on the volume implicated in abuse.
- name: sheetload_ally_certificate
- name: sheetload_ar_aging_details
- name: sheetload_books
  description: Book rating data used in @lisvinueza's data internship program.
- name: sheetload_certificates_unioned
  description: The collection of all certificates distributed by the Learning and Development team in the People group.
  columns:
  - name: completed_date
    description: The date the form was submitted.
    tests:
    - not_null
  - name: submitter_name
    description: The name of the submitter, if one was provided.
  - name: correct_responses
    description: The number of correctly submitted responses.
    tests:
    - not_null
  - name: total_responses
    description: The number of total responses submited.
    tests:
    - not_null
  - name: is_team_member
    description: A boolean flag that looks for an `@gitlab.com` email address to identify if someone is a team member.
    tests:
    - not_null
  - name: submitter_email
    description: If the person is a team member, share their email; otherwise, this is a hash.
  - name: certificate_name
    description: The name of the certificate- there are multiple kinds (Values, Ally, Certification, etc.)
    tests:
    - not_null
  - name: last_updated_at
    tests:
    - not_null
- name: sheetload_clari_forecast
- name: sheetload_clari_ai_projection
- name: sheetload_communication_certificate
- name: sheetload_compensation_certificate
- name: sheetload_data_certifications
  description: Identifies individuals who have taken the level 2 data certifications and have passed.
- name: sheetload_data_team_csat_survey_fy2021_q4
- name: sheetload_data_team_capacity
- name: sheetload_days_sales_outstanding
- name: sheetload_days_to_close
- name: sheetload_engineering_speciality_prior_to_capture
- name: sheetload_engineering_infra_prod_console_access
- name: sheetload_event_dictionary_simplified
- name: sheetload_fmm_kpi_targets
  description: Table of kpi targets for Field Marketing (FMM)
- name: sheetload_gcp_active_cud
- name: sheetload_gitlab_contributing_organizations
- name: sheetload_gitlab_slack_stats
- name: sheetload_headcount
- name: sheetload_hire_plan
- name: sheetload_hire_replan
- name: sheetload_ic_dib_comptency
- name: sheetload_ic_efficiency_competency
- name: sheetload_ic_iteration_competency
- name: sheetload_ic_results_competency
- name: sheetload_ic_transparency_competency
- name: sheetload_infrastructure_missing_employees
- name: sheetload_job_roles_prior_to_2020_02
- name: sheetload_kpi_status
- name: sheetload_linkedin_recruiter
- name: sheetload_location_factor_targets
- name: sheetload_location_factor_temporary_2020_december
- name: sheetload_manual_arr_true_up_allocation
- name: sheetload_manual_public_company_metrics
- name: sheetload_manual_downgrade_dotcom_tracking
- name: sheetload_map_ramp_deals
  description:  In Salesforce opportunity there is a field SSP ID which maps out-year ramp opportunities to its first year opportunity. However this field was introduced end of 2021 and is blank for historical. It's used by revenue accounting team, so we can't modify/backfill this field. To accurately produce financial report, we are mapping historical ramp deals manually in GSheet which will be used for different analysis and planning work.
- name: sheetload_mapping_sdr_sfdc_bamboohr
  description: Mapping table with the sfdc user id of Sales Development Representative (SDR) and their respective BambooHR id.
- name: sheetload_marketing_core_users_from_docs_gitlab_com
- name: sheetload_marketing_kpi_benchmarks
- name: sheetload_osat
- name: sheetload_percent_over_comp_band_historical
- name: sheetload_planned_values
- name: sheetload_procurement_cost_savings
- name: sheetload_product_maturity_historical
- name: sheetload_rep_quotas
  description: Sales representative quota data
- name: sheetload_rep_quotas_full_ps_fy2020
- name: sheetload_rfs_support_requests
- name: sheetload_sales_training_completion_dates
- name: sheetload_scalable_employment_values
- name: sheetload_sdr_adaptive_data
  description: Table with data for SDR ramping and status by month.
- name: sheetload_sdr_count_snapshot
  description: SDR counts by fiscal quarter and sales segment.
- name: sheetload_sdr_bdr_metric_targets
  description: Source model for SDR/BDR metric targets by metric. 
- name: sheetload_sisense_users
  description: source model for Sisense users.
- name: sheetload_sisense_user_roles
  description: source model for Sisense user roles.
- name: sheetload_social_marketing_metrics
- name: sheetload_social_marketing_topic_metrics
- name: sheetload_net_arr_net_iacv_conversion_factors
- name: sheetload_net_arr_net_iacv_conversion_factors_agg
- name: sheetload_usage_ping_metrics_sections
- name: sheetload_territory_mapping
  description: Base model for marketing territory mapping.
  columns:
    - name: segment
      tests:
        - not_null
    - name: region
      tests:
        - not_null
    - name: area
    - name: territory
      tests:
        - not_null
- name: sheetload_values_certificate
- name: sheetload_yc_companies



- name: hire_plan_xf
  description: This provides a data model of the headcount and hire planned by month broken into 3 levels - company, division, and department. This is for 2019.02 through 2020.04.
  columns:
    - name: month_date
    - name: breakout_type
      description: Identifies if the plan is at a department or division level, or aggregated up to all company.
    - name: department
    - name: division
    - name: planned_headcount
    - name: planned_hires
      description: This is calculated based on the difference between the month_date and the month prior.

- name: hire_replan_xf
  description: This provides a data model of the headcount and hire planned by month broken into 3 levels - company, division, and department. This combines the hire_plan_xf model for data between 2019.02 and 2020.05, and uses rehire_plan from 2020.06 onwards. The headcount plan was changed in 2020 to account for COVID impact.
  columns:
    - name: month_date
      tests:
        - not_null
    - name: breakout_type
      description: Identifies if the plan is at a department or division level, or aggregated up to all company.
      tests:
        - not_null
    - name: department
      tests:
        - not_null
    - name: division
    - name: planned_headcount
    - name: planned_hires
      description: This is calculated based on the difference between the month_date and the month prior.

- name: data_team_milestone_capacity
  description: This data model represents the capacity of each data team member per milestone.
  columns:
    - name: milestone_title
    - name: milestone_start_date
    - name: milestone_due_date
    - name: milestone_status
    - name: data_team_member_gitlab_handle
    - name: data_team_member_capacity
- name: sheetload_sales_capacity_kpi
  descritpion: This is the model captures sales capacity kpis target and actual
- name: sheetload_sales_funnel_targets_matrix
  description: Sales funnel target Matrix
- name: sheetload_sales_funnel_partner_alliance_targets_matrix
  description: Sales funnel Matrix for partner and alliances targets
- name: sheetload_deleted_mrs
  description: Internal MR ID that were deleted and not captured by our system.
  columns:
    - name: deleted_merge_request_id
      tests:
        - not_null
        - unique
- name: sheetload_product_group_mappings
  description: This is the mapping between group, stage, and section.
  columns:
    - name: group_name
      tests:
      - not_null
      - unique
    - name: stage_name
    - name: section_name
