version: 2

sources:
  - name: bizible
    database: '{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}'
    schema: bizible
    loader: Airflow
        
    quoting:
      database: true
      schema: false
      identifier: false

    freshness:
      error_after: {count: 36, period: hour}

    tables:
      - name: biz_accounts
      - name: biz_account_to_emails
      - name: biz_activities
      - name: biz_ads
      - name: biz_advertisers
      - name: biz_ad_accounts
      - name: biz_ad_campaigns
      - name: biz_ad_groups
      - name: biz_ad_providers
      - name: biz_attribution_touchpoints
      - name: biz_campaign_members
      - name: biz_channels
      - name: biz_contacts
      - name: biz_conversion_rates
      - name: biz_costs
      - name: biz_creatives
      - name: biz_crm_events
      - name: biz_crm_tasks
      - name: biz_currencies
      - name: biz_customer_ab_tests
      - name: biz_email_to_visitor_ids
      - name: biz_facts
      - name: biz_form_submits
      - name: biz_keywords
      - name: biz_leads
      - name: biz_lead_stage_transitions
      - name: biz_opportunities
      - name: biz_opp_stage_transitions
      - name: biz_page_views
      - name: biz_placements
      - name: biz_segments
      - name: biz_sites
      - name: biz_site_links
      - name: biz_stage_definitions
      - name: biz_touchpoints
      - name: biz_urls
      - name: biz_user_touchpoints
      - name: biz_web_host_mappings
