version: 2

models:
  - name: categories_yaml_acquisitions
    description: Identifies the acqusitions based on the [categories.yml file](https://gitlab.com/gitlab-com/www-gitlab-com/blob/master/data/categories.yml) in the GitLab Handbook.
    columns:
      - name: category_name
      - name: category_stage
      - name: snapshot_date
      - name: acquisition_key
      - name: acquisition_name
      - name: acquisition_start_date
      - name: acquisition_end_date
  - name: categories_yaml_historical
    description: This is the base table built on the snapshots of the [categories.yml file](https://gitlab.com/gitlab-com/www-gitlab-com/blob/master/data/categories.yml) in the GitLab Handbook.
    columns:
      -   name: snapshot_date
          tests:
            - not_null
  - name: categories_yaml_latest
    description: This is the latest version of the [categories.yml file](https://gitlab.com/gitlab-com/www-gitlab-com/blob/master/data/categories.yml) in the GitLab Handbook, pulled from the historical base table.
    columns:
      -   name: snapshot_date
          tests:
            - not_null

  - name: feature_flags_yaml_historical
    description: This is the base table built on the snapshots of all feature flags
    columns:
      - name: name
      - name: type
      - name: group
      - name: milestone
      - name: is_default_enabled

  - name: feature_flags_yaml_latest
    description: This is the latest version of all existing feature flags
    columns:
      - name: name
      - name: type
      - name: group
      - name: milestone
      - name: is_default_enabled

  - name: flaky_tests_historical
    description: This is the base table built on the snapshots of all flaky tests
    columns:
      - name: hash
        tests:
          - not_null
      - name: example_id
      - name: file
      - name: line
      - name: description
      - name: last_flaky_job
      - name: last_attempts_count
      - name: flaky_reports
      - name: first_flaky_at
      - name: last_flaky_at
      - name: feature_category

  - name: flaky_tests_latest
    description: This is the latest version of all existing flaky tests
    columns:
      - name: hash
        tests:
          - not_null
      - name: example_id
      - name: file
      - name: line
      - name: description
      - name: last_flaky_job
      - name: last_attempts_count
      - name: flaky_reports
      - name: first_flaky_at
      - name: last_flaky_at
      - name: feature_category

  - name: performance_indicators_yaml_historical
    description: Legacy model providing a UNIONed table of data from PI yaml files, starting 2022-08-18. This table has been replaced by [`prep_performance_indicators_yaml`](https://dbt.gitlabdata.com/#!/model/model.gitlab_snowflake.prep_performance_indicators_yaml)
    columns:
      - name: _dbt_source_relation
        description: Data source (in Snowflake) for performance indicator data (ex. `"PREP".gitlab_data_yaml.performance_indicators_ops_section_source`)
      - name: unique_key
        description: The unique composite ID for the PI's historical record, consisting of pi_name, org_name, pi_definition, is_key, is_public, is_embedded, pi_target, pi_metric_target_name, pi_monthly_recorded_targets, pi_monthly_estimated_targets, and pi_url. This ID is generated by the [`create_pi_source_table` macro](https://dbt.gitlabdata.com/#!/macro/macro.gitlab_snowflake.create_pi_source_table) in the source models.
      - name: pi_name
        description: The `name` field from the PI yaml files
      - name: org_name
        description: The `org` field from the PI yaml files
      - name: pi_definition
        description: The `definition` field from the PI yaml files
      - name: is_key
        description: The `is_key` field from the PI yaml files
      - name: is_primary
        description: The `is_primary` field from the PI yaml files
      - name: is_public
        description: The `public` field from the PI yaml files
      - name: is_embedded
        description: Boolean flag set to True if the performance indicator has a chart embedded in the handbook, based on the `sisense_data` field in the PI yaml files. This is defined as `sisense_data IS NOT NULL`
      - name: pi_target
        description: The `target` field in the PI yaml files
      - name: pi_metric_target_name
        description: The `target_name` field in the PI yaml files
      - name: pi_monthly_recorded_targets
        description: The `monthly_recorded_targets` field in the PI yaml files
      - name: pi_monthly_estimated_targets
        description: The `monthly_estimated_targets` field in the PI yaml files
      - name: pi_metric_name
        description: The `metric_name` field in the PI yaml files
      - name: telemetry_type
        description: The `telemetry_type` field in the PI yaml files
      - name: pi_url
        description: The `urls` field from the PI yaml files
      - name: sisense_chart_id
        description: The `chart` value from the `sisense_data` field of the PI yaml files
      - name: sisense_dashboard_id
        description: The `dashboard` value from the `sisense_data` field of the PI yaml files
      - name: snapshot_date
        description: The date the snapshot record was created
      - name: date_first_added
        description: This identifies when the PI was first added. Note, since we started capturing the data on 2020-08-18, this will be the date for all performance indicators that existed before data collection started.
      - name: valid_from_date
        description: The first date the record was valid (YYYY-MM-DD). This column can be used to order the different "versions" of a record. This value is used to dedupe records.
      - name: valid_to_date
        description: The last date the record was valid (YYYY-MM-DD)

  - name: roles_yaml_historical
    description: This is the base table built on the snapshots of the [roles.yml file](https://gitlab.com/gitlab-com/www-gitlab-com/blob/master/data/roles.yml) in the GitLab Handbook.
    columns:
      -   name: snapshot_date
          tests:
            - not_null
  - name: roles_yaml_latest
    description: This is the latest snaphsot of the [roles.yml file](https://gitlab.com/gitlab-com/www-gitlab-com/blob/master/data/roles.yml) in the GitLab Handbook.
    columns:
      -   name: snapshot_date
          tests:
            - not_null

  - name: stages_groups_yaml_historical
    description: Snapshots of the [stages.yml file](https://gitlab.com/gitlab-com/www-gitlab-com/blob/master/data/stages.yml) with groups parsed out.
    columns:
      - name: snapshot_date
        tests:
          - not_null

  - name: stages_groups_yaml_latest
    description: The latest snapshot of the [stages.yml file](https://gitlab.com/gitlab-com/www-gitlab-com/blob/master/data/stages.yml) with groups parsed out.
    columns:
      - name: snapshot_date
        tests:
          - not_null

  - name: stages_yaml_historical
    description: Snapshots of the [stages.yml file](https://gitlab.com/gitlab-com/www-gitlab-com/blob/master/data/stages.yml).
    columns:
      - name: snapshot_date
        tests:
          - not_null

  - name: stages_yaml_latest
    description: The latest snapshot of the [stages.yml file](https://gitlab.com/gitlab-com/www-gitlab-com/blob/master/data/stages.yml).
    columns:
      - name: snapshot_date
        tests:
          - not_null

  - name: team_yaml_historical
    description: This is the base table built on the snapshots of the [team.yml file](https://gitlab.com/gitlab-com/www-gitlab-com/blob/master/data/team.yml) in the GitLab Handbook.
    columns:
      -   name: snapshot_date
          tests:
            - not_null
  - name: team_yaml_historical_counts
    description: This a csv loaded by dbt seed for historical counts of Backend and Frontend Maintainers and Engineers. This is maintained by Sean Mcgivern.
  - name: team_yaml_latest
    description: This is the latest version of the [team.yml file](https://gitlab.com/gitlab-com/www-gitlab-com/blob/master/data/team.yml) in the GitLab Handbook, pulled from the historical base table.
    columns:
      -   name: snapshot_date
          tests:
            - not_null  
