version: 2

models:
    - name: saas_usage_ping_instance
      tags: ["product", "service_ping"]
      description: '{{ doc("saas_usage_ping_instance") }}'
      columns:
        - name: saas_usage_ping_gitlab_dotcom_id
          description: unique identifier (combine `ping_date` + `run_results` columns)
          tests:
            - not_null
            - unique
        - name: query_map
          description: json file structure with list of SQL queries executed
          tests:
            - not_null
        - name: run_results
          description: json file structure with list of SQL result as a product of execution in `query_map` column
          tests:
            - not_null
        - name: ping_date
          description: Actual date when ping is executed and data is extracted into Data Warehouse. This value determinates when data is processed.
          tests:
            - not_null
        - name: run_id
          description: Unique identifier of the run
          tests:
            - not_null
        - name: recorded_at
          description: Timestamp when original file is recorded (from the original .json file)
        - name: version
          description: App version (from the original .json file)
        - name: edition
          description: Edition type (from the original .json file)
        - name: recording_ce_finished_at
          description: Timestamp when CE recording is finished (from the original .json file)
        - name: recording_ee_finished_at
          description: Timestamp when EE recording is finished (from the original .json file)
        - name: uuid
          description: unique number from API (from the original .json file)
        - name: _uploaded_at
          description: Date and time of when data is uploaded into Data Warehouse
          tests:
            - not_null
    - name: instance_sql_errors
      tags: ["product", "service_ping"]
      description: '{{ doc("instance_sql_errors") }}'
      columns:
        - name: run_id
          tests:
            - not_null
        - name: sql_errors
          tests:
            - not_null
        - name: ping_date
          tests:
            - not_null
        - name: uploaded_at
          tests:
            - not_null
    - name: instance_redis_metrics
      tags: ["product", "service_ping"]
      description: '{{ doc("instance_redis_metrics") }}'
      columns:
        - name: saas_usage_ping_redis_id
          description: Primary key for instance redis metrics reprsent as unique combination from ping_date + run_id columns
          tests:
            - not_null
            - unique
        - name: response
          description: File with the metrics data stored in `.json` format
          tests:
            - not_null
        - name: ping_date
          description: Actual date when ping is executed and data is extracted into Data Warehouse. This value determinates when data is processed.
          tests:
            - not_null
        - name: run_id
          description: Unique identifier for running job acquiring the data
          tests:
            - not_null
        - name: recorded_at
          description: Timestamp when original file is recorded (from the original .json file)
        - name: version
          description: App version (from the original .json file)
        - name: edition
          description: Edition type (from the original .json file)
        - name: recording_ce_finished_at
          description: Timestamp when CE recording is finished (from the original .json file)
        - name: recording_ee_finished_at
          description: Timestamp when EE recording is finished (from the original .json file)
        - name: uuid
          description: unique number from API (from the original .json file)
        - name: _uploaded_at
          description: Date and time when data is uploaded into Snowflake
          tests:
            - not_null
    - name: saas_usage_ping_namespace
      tags: ["product", "service_ping"]
      description: '{{ doc("saas_usage_ping_namespace") }}'
      columns:
        - name: saas_usage_ping_gitlab_dotcom_namespace_id
          tests:
            - not_null
            - unique
    - name: instance_combined_metrics
      tags: ["product", "service_ping"]
      description: '{{ doc("instance_combined_metrics") }}'
      columns:
        - name: id
          tests:
            - not_null
            - unique
